### ISSUE TITLE
Style node label toggle button

### ISSUE THREAD

**Issue by bzurkowski** [openrca/orca-ui#100]
The node label toggle button should match the UI color scheme.

**Comment by bzurkowski** [comment]
@filwie I guess the CSS class responsible for the button styling is:

<img width="1385" alt="Screenshot 2020-09-22 at 15 14 33" src="https://user-images.githubusercontent.com/6787563/93887000-68412980-fce6-11ea-9baf-d3006fb286f5.png">

**Comment by filwie** [comment]
It's been done for a while now
