### ISSUE TITLE
Redundant SVG elements

### ISSUE THREAD

**Issue by k-jano** [openrca/orca-ui#117]
After regenerating graph on the page appears additional SVG elements, which covers previous one. Previous elements should be deleted or new elements shouldn't be generated if previous exist. This bug causes a drastic drop in a performance.
 
As you can see in the picture, I added two additional types in type selector and 2 additional elements for each previous existing node was generated.

![SVGbug](https://user-images.githubusercontent.com/37223468/95981602-302d9200-0e1f-11eb-9a67-db5b6b5ae672.png)

Probably related issue #64.

**Comment by bzurkowski** [comment]
@k-jano Good catch! 👍  Let's try to debug in the next iteration as part of #4.

**Comment by bzurkowski** [comment]
Fixed in #123.
