### ISSUE TITLE
Full node details cause the UI to fail

### ISSUE THREAD

**Issue by bzurkowski** [openrca/orca-ui#120]
After enabling full node details in the payload of Graph API, UI failed to display node details. The graph was rendered properly, however, after clicking on any node representing a pod object, the UI failed with an empty screen:

<img width="1440" alt="Screenshot 2020-10-15 at 20 06 15" src="https://user-images.githubusercontent.com/6787563/96169093-ebd6ea80-0f21-11eb-92e0-9410eb147e54.png">

Attaching graph payload which caused the failure: [graph-payload.zip](https://github.com/openrca/orca-ui/files/5386887/graph-payload.zip).

**Comment by k-jano** [comment]
Closed via #131
