### ISSUE TITLE
Load graph structure from Mock API

### ISSUE THREAD

**Issue by bzurkowski** [openrca/orca-ui#13]
Load graph payload (nodes, links) from the Mock API.

Normalize payload into a format compatible with D3.js.

Display the obtained graph structure using current graph layout.

**Comment by bzurkowski** [comment]
Recently found a helper function in D3 hierarchy library: [stratify](https://github.com/d3/d3-hierarchy#stratify). It converts a tabular (CSV-like) data structure into a format accepted by D3.js. I'm not sure if it is suitable for the OpenRCA graph payload. Just pasting in case it's helpful  😄

**Comment by k-jano** [comment]
Thank you for suggestion! Finally I managed to load graph from Mock API using [force layout](https://www.d3indepth.com/force-layout/).
