### ISSUE TITLE
Double icons

### ISSUE THREAD

**Issue by bzurkowski** [openrca/orca-ui#64]
Large icons reveal doubled icons:

<img width="1440" alt="Screenshot 2020-08-07 at 20 05 42" src="https://user-images.githubusercontent.com/6787563/89675034-86df9280-d8e9-11ea-8eb5-77712f8b3b27.png">

**Comment by filwie** [comment]
Strange thing - they seem to be doubled only after FIRST change of namespace. Is this behavior the same in your case as well? I will investigate!

**Comment by bzurkowski** [comment]
@filwie Exactly. The issue occurs only after the first namespace change, after the second change the issue is gone.

**Comment by k-jano** [comment]
Small correction, I noticed that the problem occurs every time you change original view (all namespaces) for any other one.

**Comment by filwie** [comment]
Closed by #95
